# Generated by Django 2.2 on 2019-05-06 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_header_title', models.CharField(max_length=255)),
                ('about_header_text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AboutItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_Item_fav_class', models.CharField(max_length=255)),
                ('about_item_title', models.CharField(max_length=255)),
                ('about_item_text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ContactCTA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_cta', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ContactHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_header_title', models.CharField(max_length=255)),
                ('contact_header_text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CTA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cta_image_url', models.ImageField(upload_to='media/')),
                ('cta_title', models.CharField(max_length=255)),
                ('cta_text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GalleryHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_header_title', models.CharField(max_length=255)),
                ('gallery_header_text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_item_image_url', models.ImageField(upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='NavLogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nav_logo_fav_class', models.CharField(max_length=255, null=True)),
                ('nav_logo_text', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServicesHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services_header_title', models.CharField(max_length=255)),
                ('services_header_text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ServicesItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services_Item_fav_class', models.CharField(max_length=255)),
                ('services_item_title', models.CharField(max_length=255)),
                ('services_item_text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SiteHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_header_image_url', models.ImageField(upload_to='media/')),
                ('site_header_title', models.CharField(max_length=255)),
                ('site_header_text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SliderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_image_url', models.ImageField(upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testimonial_image_url', models.ImageField(upload_to='media/')),
                ('testimonial_title', models.CharField(max_length=255)),
                ('testimonial_text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TestimonialsHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testimonials_header_title', models.CharField(max_length=255)),
                ('testimonials_header_text', models.CharField(max_length=255)),
            ],
        ),
    ]
