# Generated by Django 2.2 on 2019-05-07 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cta',
            name='cta_image_url',
            field=models.CharField(max_length=2083),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='gallery_item_image_url',
            field=models.CharField(max_length=2083),
        ),
        migrations.AlterField(
            model_name='siteheader',
            name='site_header_image_url',
            field=models.CharField(max_length=2083),
        ),
        migrations.AlterField(
            model_name='slideritem',
            name='slider_image_url',
            field=models.CharField(max_length=2083),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='testimonial_image_url',
            field=models.CharField(max_length=2083),
        ),
    ]
